global using PokerPlanning.Client.Services;
global using Blazored.LocalStorage;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using MudBlazor;
global using MudBlazor.Services;
global using PokerPlanning.Client;
global using PokerPlanning.Shared;
global using Microsoft.AspNetCore.SignalR.Client;
global using Microsoft.AspNetCore.Components;
global using static PokerPlanning.Shared.Enums;
global using PokerPlanning.Client.Services.Interfaces;