name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.4.2
    
    - name: Setup .Net 6  
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        include-prerelease: false
    
    - name: Publish .NET Core Project
      run: dotnet publish PokerPlanning.sln -c Release -o release --nologo
    
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
      with:
        FOLDER: release/wwwroot

